# Generated by Django 3.2.4 on 2021-06-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], max_length=10, null=True)),
                ('branch', models.CharField(choices=[('Select', 'Select'), ('ECE', 'ECE'), ('CSE', 'CSE'), ('MEC', 'MEC'), ('IT', 'IT'), ('CIVIL', 'CIVIL')], max_length=10, null=True)),
            ],
        ),
    ]
